FROM dataloopai/dtlpy-agent:gpu.cuda.11.8.py3.10.pytorch2

RUN pip install --user \
    dtlpy \
    scikit-image \
    tensorflow==2.10.0 \
    scipy \
    python-dotenv \
    openai \
    opencv-python